-- GRUPO 4
-- Marcelo Garofalo
-- Rhuam Bello Carneiro
-- Manuel Jose Pinero
-- Joaderson Felipe Silva Barbosa
-- Michel Picozzi
-- Cintia Rodrigues Moreira

CREATE SCHEMA IF NOT EXISTS DHTUBE;
USE DHTUBE;

CREATE TABLE IF NOT EXISTS AVATAR (
  ID_AVATAR INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(45),
  URL_IMAGEM VARCHAR(100),
  PRIMARY KEY (ID_AVATAR));
  
CREATE TABLE IF NOT EXISTS PAIS (
  ID_PAIS INT NOT NULL AUTO_INCREMENT,
  NOME_PAIS VARCHAR(100),
  PRIMARY KEY (ID_PAIS));

CREATE TABLE IF NOT EXISTS USUARIO (
  ID_USUARIO INT NOT NULL AUTO_INCREMENT,
  NOME_USUARIO VARCHAR(45),
  EMAIL_USUARIO VARCHAR(45),
  SENHA_USUARIO VARCHAR(45),
  DATA_NASCIMENTO DATETIME,
  CEP_USUARIO VARCHAR(45),
  ID_PAIS INT NOT NULL,
  ID_AVATAR INT NOT NULL,
  PRIMARY KEY (ID_USUARIO),
  CONSTRAINT FKID_PAIS
  FOREIGN KEY (ID_PAIS)
  REFERENCES DHTUBE.PAIS(ID_PAIS),
  CONSTRAINT FKID_AVATAR
  FOREIGN KEY (ID_AVATAR)
  REFERENCES DHTUBE.AVATAR(ID_AVATAR)
  );
 
 CREATE TABLE IF NOT EXISTS CANAL (
  ID_CANAL INT NOT NULL AUTO_INCREMENT,
  NOME_CANAL VARCHAR(45),
  DESCRICAO_CANAL TEXT,
  DATA_CRIACAO_CANAL DATETIME,
  ID_USUARIO INT NOT NULL,
  PRIMARY KEY (ID_CANAL),
  CONSTRAINT FKID_USUARIO
  FOREIGN KEY (ID_USUARIO)
  REFERENCES DHTUBE.USUARIO(ID_USUARIO)
  );
  
CREATE TABLE IF NOT EXISTS VIDEO (
  ID_VIDEO INT NOT NULL AUTO_INCREMENT,
  ID_USUARIO INT NOT NULL,
  TITULO_VIDEO VARCHAR (100),  
  DESCRICAO_VIDEO TEXT,
  TAMANHO_VIDEO DOUBLE,
  NOME_ARQUIVO_VIDEO VARCHAR(100),
  DURACAO_VIDEO DOUBLE,
  IMAGEM_VIDEO VARCHAR(100),
  QTD_REPRODUCOES_VIDEO INT NOT NULL,
  QTD_LIKES_VIDEO INT,
  QTD_DISLIKES_VIDEO INT,
  PRIVADO_VIDEO SMALLINT,
  DATA_PUBLICACAO_VIDEO DATETIME,
  PRIMARY KEY (ID_VIDEO),
  CONSTRAINT FKID_USUARIO2
  FOREIGN KEY (ID_USUARIO)
  REFERENCES DHTUBE.USUARIO(ID_USUARIO)
);

CREATE TABLE IF NOT EXISTS PLAYLIST (
  ID_PLAYLIST INT NOT NULL AUTO_INCREMENT,
  NOME_PLAYLIST VARCHAR(45),
  DATA_CRIACAO_PLAYLIST DATETIME,
  PRIVADO_PLAYLIST SMALLINT,
  ID_USUARIO INT NOT NULL,
  PRIMARY KEY (ID_PLAYLIST),
  CONSTRAINT FKID_USUARIO_PLAYLIST
  FOREIGN KEY (ID_USUARIO)
  REFERENCES DHTUBE.USUARIO(ID_USUARIO)
  );
  
  CREATE TABLE IF NOT EXISTS PLAYLIST_VIDEO (
  ID_PLAYLIST INT NOT NULL,
  ID_VIDEO INT NOT NULL,
  CONSTRAINT FKID_PLAYLIST
  FOREIGN KEY (ID_PLAYLIST)
  REFERENCES DHTUBE.PLAYLIST(ID_PLAYLIST),
  CONSTRAINT FKID_VIDEO
  FOREIGN KEY (ID_VIDEO)
  REFERENCES DHTUBE.VIDEO(ID_VIDEO)
  );
